### ISSUE TITLE
[BUG] error: Recipe `initdb` failed on line 7 with exit code 1

### ISSUE THREAD

**Issue by PassLass** [Nukesor/ultimate-poll-bot#108]
I have a this bug:
Help me

![Screenshot from 2022-11-04 13-09-03](https://user-images.githubusercontent.com/65995394/200065879-a3181511-9d34-4eb9-96bf-73511bb4453c.png)

**Comment by PassLass** [comment]
It has something to do with localhost?

**Comment by Nukesor** [comment]
Seems like your postgresql URL is wrong:

`postgresql://{user}[:{password}]@{host}[:{port}]/{db_name}`

**Comment by PassLass** [comment]
Tell me where and how do I need to change the database URL?

**Comment by Nukesor** [comment]
For more information, please read the [Architecture Guide](https://github.com/Nukesor/ultimate-poll-bot/blob/main/ARCHITECTURE.md)
