### ISSUE TITLE
[BUG] Command `git clone git@github.com:nukesor/ultimate-poll-bot pollbot && cd pollbot` doesn't work

### ISSUE THREAD

**Issue by PassLass** [Nukesor/ultimate-poll-bot#109]
I have this error:

`Warning: Permanently added 'github.com,140.82.121.3' (ECDSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

**Comment by Nukesor** [comment]
Please read the guide on how to use git and ssh keys in combination with github or git in general.

https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account
