### ISSUE TITLE
[bug] "Add new option" deeplink opens date picker

### ISSUE THREAD

**Issue by RememberTheAir** [Nukesor/ultimate-poll-bot#17]
**Steps to reproduce**
1. create a poll
2. enable "enable users to add new options" setting
3. share the poll
4. open the "add new option" url in the inline url button

Once you click on "start", the bot asks you to pick a date instead of asking you for the new option ([video](https://telegra.ph/file/94eff739c26d300d2c0cf.mp4) of the issue)

**Comment by Nukesor** [comment]
Thanks for this report. I fixed this in the course of this commit https://github.com/Nukesor/ultimate-poll-bot/commit/f6c132e15221460f88659ed0bde77795be3609b7
