### ISSUE TITLE
[enhancement] more explicit warning when making a poll anonymous

### ISSUE THREAD

**Issue by RememberTheAir** [Nukesor/ultimate-poll-bot#19]
Right now there's a pretty explicit message on the "turn poll permanently anonymous" button, but I think it would be nice to have an explicit message in the message text saying **you can't get back** to a non-anonymous poll. It feels like that "permanently" in the inline button is not explicit enough. Just a personal opinion, feel free to close this issue

**Comment by Nukesor** [comment]
Ok. I'll briefly add this :) Thanks for the feedback!

**Comment by Nukesor** [comment]
Ok. I just looked into the code and I found that there already is a pretty explicit message there :D
![image](https://user-images.githubusercontent.com/3322822/61185688-6ef0fd00-a65c-11e9-9816-b9fe0b185e2a.png)

Or do you mean that it should be more explicit during poll creation?

**Comment by RememberTheAir** [comment]
@Nukesor oh, never mind. I might have not seen it
