### ISSUE TITLE
[bug] bot is unresponsive when an user without username votes

### ISSUE THREAD

**Issue by RememberTheAir** [Nukesor/ultimate-poll-bot#29]
Hello,

I just tried the new update and, apparently, the bot doesn't correctly process votes from users without an username.

I think I spotted the bug: [here](https://github.com/Nukesor/ultimate-poll-bot/commit/53cbf830d5ec680ff1c9b5f538298675da034f50#diff-ff1d97b7e0fbd92bc538da23ede9dc54R75) you can see that the bot tries to `lower()` the `username` attribute of an user (which I assume is a python-telegram-bot's `User` object), which is `None` for users without an username

**Comment by Nukesor** [comment]
Damn, you're right. I must have deleted that check somehow during the refactoring.
Should be fixed by now.
