### ISSUE TITLE
Inconsistent wording for toggles

### ISSUE THREAD

**Issue by jlsjonas** [Nukesor/ultimate-poll-bot#31]
The wording between the current status and the button is inconsistent between anonymous status & result display
The (IMHO) expected correct wording is for anonymous: "anonimize poll" when the poll is currently set to show names

However for visible results the button shows "hide results until poll is closed" when the current state is that already, and vice-versa

**Comment by Nukesor** [comment]
You're totally right. This little bug was introduced in the process of adding translations and multiple languages for the bot...
Thanks for the report, it should be fixed in a minute!
