### ISSUE TITLE
Show week day in date vote button text

### ISSUE THREAD

**Issue by MrGreenTea** [Nukesor/ultimate-poll-bot#40]
Love the bot, thanks for the great work. It would be really helpful for me if the dates in the bot's vote buttons could be shown with the weekday similar to how they are displayed in the poll overview.

**Comment by Nukesor** [comment]
Hm. I like the idea. I'll add it right away

**Comment by Nukesor** [comment]
Implemented and online with https://github.com/Nukesor/ultimate-poll-bot/commit/8f855cf41327c7e0c473511ac7ef6562bd31eb68
