### ISSUE TITLE
[bug] "hide percentage" styling option will loose mentions of users without an username

### ISSUE THREAD

**Issue by RememberTheAir** [Nukesor/ultimate-poll-bot#42]
**Steps to reproduce:**

1. create a poll and keep the default styling settings
2. share it and let people vote (important: someone without an username should vote)
3. go to the poll's styling settings
4. use the "hide percentages" to hide the percentage bar and number

Result: mentions of the user that voted are lost **but only in the poll preview message**. If you share the vote in a group chat and hide the percentages, the mentions are not lost in the message posted in the group. They'll only be lost in the chat with the bot

**Comment by Nukesor** [comment]
That's weird.
I cannot reproduce it for now, since I don't have a poll that has votes from a user without a username.
I'll keep an eye on it, though.

**Comment by Nukesor** [comment]
Is this still an issue? I still haven't seen any occurrences
