### ISSUE TITLE
allow to set a maximum number of votes per option

### ISSUE THREAD

**Issue by calestyo** [Nukesor/ultimate-poll-bot#43]
Hi.

Parts of the Pokemon Go community use your bot to set up lists on Telegram.

It would be handy if it was possible for a creator to set a maxmimum number of votes per option, so that e.g. 20 users could join option 1 and would then have to go on with options 2.

Cheers,
Chris.

**Comment by Nukesor** [comment]
Sounds like an interesting idea.
This is probably something that would need to be configurated after creating the poll.
I already got several complaints, that the creation interface is already too complex for the "normal" user.

That's why I'm careful with adding new styling/behaviour options.

**Comment by calestyo** [comment]
Well.. it's the ultimate poll bot... not the beginner's poll bot ;-)
But thanks for consideration.

**Comment by Nukesor** [comment]
Yep :D
It's designed with power users, but the interface should still be intuitive and easy to use, if you don't want to create the most customized poll ever conceived :D

I think this is something that could be added to the bot. We just need to find a way to integrate it in a nice way :)

**Comment by Nukesor** [comment]
1. Add a new menu during creation (Advanced settings). We can hide a lot of stuff in here. That's the easy part
2. We need to check and extend the whole voting logic. There are several distinct voting handlers, for the eifferent poll types. That's going to be a major feature with a few possibilities to introduce bugs
