### ISSUE TITLE
allow to disable the last line, suggesting how to create own polls

### ISSUE THREAD

**Issue by calestyo** [Nukesor/ultimate-poll-bot#44]
Hi.

In our community the last line, suggesting how to create own polls, confused some older users.
It would be nice if this could be disabled. 

Cheers,
Chris.

**Comment by Nukesor** [comment]
Ok. That sounds fair. Thought that this might increase the traction of the bot a little ;D.

I'm not sure, when I'll implement this tough. Feel free to create PR's for your issues :)
I'll happily answer any questions.

**Comment by calestyo** [comment]
In most places where I post polls via the bot, Telegram anyway says "via @ultimate_pollbot" or so... so anyone who is interested can still find the bot. :-)
