### ISSUE TITLE
allow to change the text for "n votes"

### ISSUE THREAD

**Issue by calestyo** [Nukesor/ultimate-poll-bot#45]
Hi.

Parts of the Pokemon Go community use your bot to set up lists on Telegram.

There it's not really "votes" what an option counts... but rather users... thus it would be nice if this could be customised to another text.

Cheers,
Chris.

**Comment by Nukesor** [comment]
Whew. TBH that's pretty specific.
I'm already struggling to keep the interface from being cluttered.
This styling option is probably really niche and would further increase complexity in the interface as well as the poll display behavior (which is already quite complex).
I'm not sure if it's worth it. As far as I understand, it's simply a issue with the wording?

**Comment by calestyo** [comment]
Yeah it's purely cosmetic.
