### ISSUE TITLE
bot seems down

### ISSUE THREAD

**Issue by calestyo** [Nukesor/ultimate-poll-bot#48]
Hi.

Not really a bug, but the bot seems to be down and doesn't reply on Telegram.

Cheers,
Chris.

**Comment by Nukesor** [comment]
Issue is just being resolved. Should be up and running in a few minutes again :)
Thanks for reporting!

**Comment by calestyo** [comment]
Thanks for fixing... but it seems that all pools I've created since yesterday night are gone (not a big deal tough for me)

**Comment by Nukesor** [comment]
Weird. That shouldn't have happened. Can't imagine how that could have happen either...
Once it's in the database, it doesn't get deleted (unless explicitly deleted by you).

There's nothing I could do about that, anyway...

**Comment by calestyo** [comment]
Anyway... as I've said.. doesn't really matter :-D
