### ISSUE TITLE
Allow editing of messages during poll creation

### ISSUE THREAD

**Issue by Nukesor** [Nukesor/ultimate-poll-bot#51]
The bot should detect, whether messages are edited during creation and update the respective texts accordingly.

- New Entity (`InputMessage`?)
    -> Poll_id
    -> message_id
    -> Type of message (text, description, options)
- Editing only works during poll creation
- New message handler for editing messages in private chats
-> Check whether we know this message and whether the associated poll has already been created
- Update the text

Editing of poll options could be a problem, since the update of a option title probably results in a new option, rather than an updated one.

In general this is no easy problem. What happens, if some option in a multiline message is edited, but another option above is removed. It's super hard to detect, which option name has been edited, as soon as we are handling multi line messages.

For proper handling, we would need to save the original message in the database as well.
#discussion

**Comment by SmartManoj** [comment]
Messages or options
