### ISSUE TITLE
Remember last used settings or global settings

### ISSUE THREAD

**Issue by skvrnda** [Nukesor/ultimate-poll-bot#57]
I create 5 polls per week and those polls have always the same settings.
Every poll I create, I have to make aways the same settings.
It will be nice, if the bot stores something like default settings for each new poll or just to remember last used settings.

Thanks

**Comment by Nukesor** [comment]
That's already the case for a few settings (language etc.)
I would suggest to add a default poll settings option to the user /start interface.
I don't like the idea of changing your default settings, when changing settings in a poll.

For instance, I use several kinds of polls and I have different settings for different groups.
If the default settings would change all the time, I would be seriously confused.

Feel free to start hacking :)

**Comment by gnadelwartz** [comment]
https://github.com/Nukesor/ultimate-poll-bot/issues/61#issuecomment-596526190
