### ISSUE TITLE
Save a poll template / automate poll creation

### ISSUE THREAD

**Issue by Ammarjeddin** [Nukesor/ultimate-poll-bot#61]
I’m trying to have a template saved for the poll. 
Use case: daily poll created manually where only the title of the poll is changed.

**Comment by Nukesor** [comment]
This is another feature for the user settings tab. It's a pretty big feature, though.

Fell free to start tinkering, PRs welcome.

**Comment by gnadelwartz** [comment]
instead of template or default settings it may be easier for beginners and more flexible to have the ability to "clone" an existing poll in poll creation (without votes of course...)

**Comment by Nukesor** [comment]
This is already possible. A `clone` and `reset` button exists after the poll has been closed.

**Comment by gnadelwartz** [comment]
if this can be done for running polls (including edit of poll) it woud be perfect.

**Comment by Nukesor** [comment]
Editing of polls will never be allowed to prevent manipulation of polls.
Cloning a running poll is a feature that could be added, but I don't want to overload the poll management keyboard.

**Comment by gnadelwartz** [comment]
I thougt more about

new poll -> clone+reset -> adjust values -> run

**Comment by Nukesor** [comment]
Tracking issue #69
