### ISSUE TITLE
Problem with initializing the DB

### ISSUE THREAD

**Issue by tobikrs** [Nukesor/ultimate-poll-bot#63]
I followed the installation and starting instructions... but after running `poetry run python main.py` I get this error:
```
(psycopg2.errors.UndefinedTable) relation "update" does not exist
```

I managed to figure out that after step 4. (running `initdb.py`) no tables in the postgres database were created. So the error from above makes sense...

But why is `base.metadata.create_all()` in `initdb.py` doesn't have any effect?

Maybe something is wrong with my postgres database setup. Could this be a permission issue with the user how runs the `initdb.py` script? ...If so how to fix it?

Any suggestions?

**Comment by Nukesor** [comment]
Hm. I've seen the behavior you described a few times already, but I don't know what's causing it.

A working quick fix seems to be to drop the database and run `initdb.py` again.

I'll move the `CREATE EXTENSION` code to the bottom of the initialization, I've got a hunch that this is might be a problem, since the problem seems to only occur at the very first run of the initdb.py script on a clean database.

**Comment by tobikrs** [comment]
Thanks for the quick response!

I managed to run the `initdb.py` successfully after dropping the database... 

My mistake was to create the database `pollbot` unnecessarily by hand before running the script, which I falsely thought would not provide the creation.

**Comment by tobikrs** [comment]
> I'll move the `CREATE EXTENSION` code to the bottom of the initialization, I've got a hunch that this is might be a problem, since the problem seems to only occur at the very first run of the initdb.py script on a clean database.

Unfortunately this has to be undo because the `base.metadata.create_all()` requires the `gen_random_uuid()` function for some queries.

**Comment by Nukesor** [comment]
ah damn. Thanks for reporting! I just reverted it :)

**Comment by tobikrs** [comment]
I actually meant ba4ec931150a8953e719259302f4228fd16b2f2b to be undone... you reverted a different commit (68d16bf4023320e550f7c05966dde3fe87ea83e8)

Was this on purpose?

**Comment by Nukesor** [comment]
Damn. I should pay more attention, when quick fixing things. Thanks again.
