### ISSUE TITLE
Create a poll and distribute it to another bot's users?

### ISSUE THREAD

**Issue by davidgfnet** [Nukesor/ultimate-poll-bot#64]
Hello there!
Would be cool to be able to create a poll and get a Link, so that it can be shared to users of a particular bot (in my case I'm admin of some bots). The users would click the link (perhaps in the shape of a button) that would deep-link the selected poll back to the UPB. There they could fill in the poll and the admin of the bot could receive the results.
Does it sound like an idea worth exploring?
I wouldn't mind sending a few PRs if that makes is easier too.

**Comment by Nukesor** [comment]
Allowing other users to share polls is already possible. (There's a deep link in the Setting menu of a poll)
Is this what you had in mind?

**Comment by davidgfnet** [comment]
Yes but that link allows users to share the poll. What id like is a link that my bot can give to every user and, on clicking the link, the user is redirected to your bot to actually answer the questions (vs now where they get a Share link).
I can imagine that doing so could be tricky. Ideally having a seconday bot just to answer polls would be a good idea.
Sorry that im not explaining myself more clearly!

**Comment by Nukesor** [comment]
Ah ok. I understand. 
This functionality is already implemented for priority vote, but the deeplink is not yet displayed anywhere for other polls.
It should probably be displayed beneath the existing link in the settings menu.
The links is compiled over [here](https://github.com/Nukesor/ultimate-poll-bot/blob/master/pollbot/telegram/keyboard/vote.py#L132).
Thereby this is an really easy to implement feature, but I'll keep this on hold, until the telethon rewrite is finished (There's currently a huge transition from `python-telegram-bot` to `telethon` underway)

**Comment by davidgfnet** [comment]
Can't see the link for a priority poll. Where is it exactly? Also: why just that kind of poll has it? Thanks for the info! I was thinking on implementing this in my bot or as a separate bot but unsure, since using a bot like this one might be easier. Is the performance good? asking since it's python, not sure how scalable it is. Thanks!

**Comment by Nukesor** [comment]
The link is used in the vote button. It's only used over there, since this poll needs a special interface that only works in private chat.

Performance is ok, unless you want several hundred people voting at the exact same time.
The main problem usually comes from telegram api limitations. If many people vote at the same time the bot may be blocked, but this is a problem pretty much every semi-big bot with many buttons experiences.

**Comment by Nukesor** [comment]
After thinking some more about this, I'll definitely revert this feature and add a check to prevent these links from working on polls other than `priority`

Using this link on large polls will result in HUGE amounts of messages being sent to a huge amount of users.
This will definitely trigger telegram api limits and kill the bot.
Definitely a very bad idea. I don't think building something like this is viable. I would

**Comment by davidgfnet** [comment]
Oh ok I just tried it. It's interesting that the regular polls can have buttons, that call back to the bot directly, whereas the priority vote does not. What's the reason for that?

**Comment by Nukesor** [comment]
Every user has to order the options according to their own priorities. You cannot display different buttons for each user in group chats.

**Comment by davidgfnet** [comment]
Makes sense indeed!
What kind of limits do you think the bot could hit? I recall the limits being msg/s/conversation, so in a group chat with a lot of interactions one could indeed hit the limit if a big group of people vote right? But it would also be possible to rate limit it (I think you do that already right?)

**Comment by Nukesor** [comment]
I'm doing it to a certain extend. However, proper performance optimizations are the next feature on my to-do list.

https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this
those limits are reached pretty fast

**Comment by davidgfnet** [comment]
Oh it's cause you might need to send multiple updates when someone votes, since all the parts need an updated version of the poll. I see!
I developed my bots in C++ to avoid perf issues, since it's hard to keep up with a small server if you have too many users, particularly big bursts of users.
Hey let me know if I can somehow help with this, I'd rather not create a new bot for this nor integrate poll support in mine. Seems like an overkill to me :)

**Comment by Nukesor** [comment]
I can offer you a configuration setting, that allows private messages for your own hosted instance.

I would like to not enable this for @ultimate_pollbot, since it already has a quite big user base and a lot of requests/second.

I don't think CPU-performance is a problem, but rather requests/minute.
The performance optimizations will mostly aim to decrease requests/vote.

**Comment by Nukesor** [comment]
https://github.com/Nukesor/ultimate-poll-bot/commit/8a96c336edbad358d425fb2622eeaf8156ae1aa3

**Comment by davidgfnet** [comment]
Wow that's pretty cool!
It's cool to see there's features that can be enabled and disabled!
Would you take a PR to make the bot more private? As in: so people can run their own instance for their own polls, so that the bot doesn't allow users to create polls but only answer them. Perhaps some config knob with a username list of people who are allowed to create polls.
I see there's an "admin user" knob already, but not sure what it is for.

**Comment by Nukesor** [comment]
The admin user has some extra settings and commands.

In StickerFinder I added a similar feature, which introduced a flag `authorized` on all users.
Only user that have been authorized by the admin can then use the bot.

I guess such a feature could be handy, but I'm pretty sure I won't implement it myself.
PR's are of course welcome ;)

**Comment by davidgfnet** [comment]
Yeah of course, that I can do myself.
BTW do you have a rough estimate for the telethon branch?

**Comment by Nukesor** [comment]
I merged it into master today.
A big bug came up, which we don't have a solution for  yet, but the rest looks quite fine.

Feel free to visit the support chat :)
https://t.me/nukesors_projects

Pretty much everything is discussed in there (including the current state of the bug)
