### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by captainkirk17** [Nukesor/ultimate-poll-bot#84]
in a ranked poll created by bot,the poll doesn't not registers vote,no matter how many times you try it does not register your choice and stop to work after sometime.it does not crash simply does not do anything.

**Comment by Nukesor** [comment]
I assume you're talking about a "Priority Vote" poll?

Is there any additional information you can give me, anything extraordinarily? Maybe a huge amount of people, weird usernames or option names?

I'm regularly using priority vote polls and I couldn't reproduce your bug yet.
