### ISSUE TITLE
[BUG] Deleted Polls are still in Open Polls

### ISSUE THREAD

**Issue by sleepingc** [Nukesor/ultimate-poll-bot#86]
**Describe the bug**
_Tried to delete all my 5 polls. It says deleted but i still can send these deleted polls to group chats and people but i don't have access to control the poll as it says "poll has been deleted". so i created more to try and delete it but it still adds to the open polls but i deleted ALLLLLL polls already. I can't clear telegram cache too because the chat doesnt even come up there._

**To Reproduce**
_1. Go to '...Settings...'
2. Click on '....Delete All Polls / Delete All Closed Polls...'
3. Scroll down to '....Confirm...'
4. See error > back to 9 Open Polls that i don't have access to because i wipe the data already._

**Expected behavior**
_If i delete the open polls, both Closed Polls and Open Polls should be 0, 0 what not 0 and 9!_

**Screenshots**
![photo6242314217311021660](https://user-images.githubusercontent.com/75853398/101971014-11098000-3c69-11eb-89a1-d0854f49dbff.jpg)
![photo6242314217311021661](https://user-images.githubusercontent.com/75853398/101971020-15359d80-3c69-11eb-9e6a-1b4a57fd5b86.jpg)

**Additional context**

**Comment by Nukesor** [comment]
Jo. It's fixed.
