### ISSUE TITLE
CANNOT SEND OUT POLL...[BUG]

### ISSUE THREAD

**Issue by sleepingc** [Nukesor/ultimate-poll-bot#87]
**Describe the bug**
i appreciate that you fixed my delete data issue but u created another issue for me. i can't send out any polls now........... hOW
how do i press send???? PLS HELP..

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen if it's not obvious.

**Screenshots**
![photo6244334157610199828](https://user-images.githubusercontent.com/75853398/101986073-b0a92b80-3cc6-11eb-947e-29beb51ccca6.jpg)

**Additional context**

**Comment by Nukesor** [comment]
Yep. Accidentally made a logic error in a inline query sharing.
Should be fixed.
Thx for the bug report.
