### ISSUE TITLE
No poll sync [BUG]

### ISSUE THREAD

**Issue by nukeroni** [Nukesor/ultimate-poll-bot#90]
**Describe the bug**
After a poll is created, forwarded and sent the sync does not work. No workaround is working.

**To Reproduce**
1. Go to 'forward poll'
2. Click on 'a chat you choose'
3. Click the poll to send
4. See error "Please wait while poll is being synced. This might take a few seconds" but it doesnt happen

**Expected behavior**
The poll should be synced and appear but the message stays there.

**Screenshots**
1 Screenshot (German)
![Pollbot](https://user-images.githubusercontent.com/77064805/103810186-1a64ed00-505b-11eb-80f7-cfa554aa9755.jpg)

**Additional context**
none

**Comment by Nukesor** [comment]
Yep. The bug is actually known. It appeared a few weeks ago, but I couldn't find out why it's happening yet...
This needs further investagation. Any help is appreciated.

I assume you tried to share the poll to a private chat?
As far as I've seen, sharing to group chats still works.

**Comment by nukeroni** [comment]
Thanks for your help and reply Nukesor!

It was tried to share the poll into a group chat of about 50 participants. It was tried multiple times without sucess.

But when I tried to share a poll into a private group chat it worked after a few tries and/or a workaround that includes deleting the text after @pollbot to see the list of polls, then select to share.

Great bot! We use it frequently! Unfortunately the buy me a coffe link is unable to reach via pollbot link. Would like to support. Have a great day @Nukesor :D !

**Comment by Nukesor** [comment]
I just tried to reproduce your issue and I was indeed able to reproduce your issue.

I have a hunch why this is happening and pushed a possible fix. Please tell me, if this happens again :)

Well, I deleted my Patreon and BuyMeACoffee links :D. Maintaining them wasn't worth the time, since I barely received any donations anyway.

**Comment by nukeroni** [comment]
Thank you for your quik reply and your help Nukesor. Seems to work again. Have a great day!
We appreciate your work and really like to use the bot in our daily business, as it is a valuable tool :)

**Comment by Nukesor** [comment]
Happy to hear that :)

You're welcome
