### ISSUE TITLE
[Request] details on who voted for what option in polls

### ISSUE THREAD

**Issue by swejohn** [Nukesor/ultimate-poll-bot#94]
Today you only see the percentage of what option people voted for and the last two users who voted for a specific option in the poll.

It would be nice as admin to see who (which users) who voted for each option (not only the last two users)

Or a possibility to extract this info

**Comment by Nukesor** [comment]
This should already be possible.
Polls where too many users voted usually have a button at the bottom, which sends you to the private chat with the bot.

Over there you can then see all details about the poll.

**Comment by mthene** [comment]
Hi Nukesor,
unfortunately I can't see the names in the private chat with the bot either. Where should I see them? Do I have to end the poll beforehand? Thanks in advance. 

Poll type: Doodle
Language: German
Anonymity: Names are visible
Visible results: Results are directly visible
Due date: None
------- Styling -------
Custom user options: Only you can add new options
Percentage: Visible
Summarize votes: Too many votes. Permanently summarized.
User sorting: by answer
Option sorting: manually

**Comment by Nukesor** [comment]
In the voting menu there should be a button at the bottom:

![image](https://user-images.githubusercontent.com/3322822/124391941-5bc91300-dcf3-11eb-8e3e-8bf2b0d1e887.png)

If you click on that butt and press `Start` in the private conversation, you should see the results

**Comment by Nukesor** [comment]
This still active or can this be closed?
