### ISSUE TITLE
[BUG] - Error on sending an options on Poll Both

### ISSUE THREAD

**Issue by Mrramadhann** [Nukesor/ultimate-poll-bot#95]
**Describe the bug**
An error occured when inputing an option in a Poll Bot, already reset the poll but it seems that it has the problem with the system because it still error.

**To Reproduce**
1. Go to 'Ultimate Poll Bot'
2. Click on 'Create New Poll'
3. Scroll down to 'until it shows the description about creating a new poll, and then send the poll's name also the description about it. When it comes to a bubble "Send me an option. You can send multiple options at once, each option on a new line" write it down the options and it will shown the error'

**Expected behavior**
The option has to be shown after inputing the options on a bubble option before.

**Screenshots**
![POLL BOTH ERROR](https://user-images.githubusercontent.com/86389876/123190044-0d34a100-d4c9-11eb-9ad5-fceaac072103.png)

**Additional context**
Please fix it because it used routinely

**Comment by Nukesor** [comment]
Fixed with 1621a41
