### ISSUE TITLE
Pre-add voting name list before releasing to public

### ISSUE THREAD

**Issue by Victorlmy** [Nukesor/ultimate-poll-bot#96]
**Is your feature request related to a problem? Please describe.**
My poll only limited to certain amount of total vote, so for those who are willing to join i will have to add their name into it before releasing to the public. Because the poll will be full in a short while after released. 

**Describe the solution you'd like**
Wish to add setting option to pre-register people into voting list by admin.

**Comment by Nukesor** [comment]
To be honest, I don't quite get what you're trying to say.

Could you give a more detailed explanation on what your problem, use-case, poll type, etc. is?

**Comment by Victorlmy** [comment]
Sorry Nukesor, what i mean is there any possible way to add names into the voting list by poll creator. Eg, when people voting at the poll their name will be listed in the poll right, but would like to add names into the poll list without them to vote, and after that only share to the group for public vote.

**Comment by Nukesor** [comment]
This is sadly not possible.
People are only associated to a poll via their votes. Hence, as long as a user didn't vote, there can is no relationship between users and polls.
Sadly, there's also no way to implement this, as Telegram doesn't allow bots to view users that haven't contacted them before.

**Comment by Nukesor** [comment]
I'll close this issue, as this cannot be done :)

**Comment by Victorlmy** [comment]
Ok, thanks for replying Nukesor 👍
