### ISSUE TITLE
[Request] Autopost on channel

### ISSUE THREAD

**Issue by OverloadedTech** [Nukesor/ultimate-poll-bot#97]
Please add the possibility to add the bot on a channel to post directly form the bot the pool without using infline feature

**Comment by Nukesor** [comment]
This would need a lot of additional features, management interfaces and special handling.

This doesn't fit into the scope of the bot, as this is rather intended as a personal poll bot and not a bot for large-scale automated poll distribution in channels.

However, this is open-source. Just fork the project and write the feature yourself :)
You can always host your own instance on your own servers. Other people will probably appreciate your work quite a bit ;)
