### ISSUE TITLE
[Request] - Retract or Change Answer

### ISSUE THREAD

**Issue by gapletona** [Nukesor/ultimate-poll-bot#98]
**Is your feature request related to a problem? Please describe.**
If a user selects an answer and it is the wrong answer or later decide to change their answer, there is no way for the user to make that change.

**Describe the solution you'd like**
Regular polls in Telegram allow a user to retract their vote allowing them to vote again.

**Additional context**
Long hold context menu on poll to allow retraction of vote.

**Comment by Nukesor** [comment]
As far as I know, it's possible to unselect votes from every poll type there is.

You retract a vote, by simply clicking on the selected option once more.

**Comment by Nukesor** [comment]
There are many support poll types, which poll do you talk about.
Could you give a step-by-step explanation, so I can reproduce that behavior?

**Comment by gapletona** [comment]
I swear I tried that and it didn’t work. I’ll try again.
